name: macos-x64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos-x64:
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install
        run: |
          brew install llvm@17
          brew link --force llvm@17
          echo 'export PATH="/usr/local/opt/llvm@17/bin:$PATH"' >> /Users/runner/.bash_profile
          source /Users/runner/.bash_profile
      - name: Check installed clang
        run: |
          which clang++ && clang++ -v
          /usr/local/bin/clang++ -v
      - name: Prepare
        run: |
          source $GITHUB_WORKSPACE/scripts/prepare_macos_x64.sh
          echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
      - name: Check virtual environment
        run: |
          which clang++ && clang++ -v
          which /usr/local/bin/clang++ && /usr/local/bin/clang++ -v
          which python3 && python3 -V
          which conan && conan -v
          which cmake && cmake --version
      - name: Configure
        run: |
          cmake --preset 'conan-debug'
      - name: Build
        run: |
          make -j$(sysctl -n hw.ncpu) -C $GITHUB_WORKSPACE/build/Debug/
      - name: Run tests
        run: |
          make -j$(sysctl -n hw.ncpu) test -C $GITHUB_WORKSPACE/build/Debug/